# StrategyConfig.py
# Define a list of strategy configurations

# Credentials
CLIENT_ID = '11198_muJeK9dYaCwseaddKNqqXpDIDbdOgjuQxnB359f6AvNfy8O0iN'
CLIENT_SECRET = 'QXOiXKbeENK9LP1WmnvU4itS5FcrSTi935TlX8TTx0zqRyVmhg'
ACCESS_TOKEN = 'l25u-D76EvcDnPbzNnXl21PGDsahPTNoV4a6sGmjkkc'
ACCOUNT_ID = 19650220  # Demo account ID

strategies = [
    {
        'label': 'HHLL_AEX_1H',
        'symbol_id': 10036,  
        'symbol_precision': 2,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/AEX_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_AEX_1H.py',
        'buy_offset_percentage': 0.05,
        'sell_offset_percentage': 0.05,
        'stop_loss_percentage': 0.685,
        'take_profit_percentage': 0,
        'volume': 103,  
    },
    {
        'label': 'HHLL_NZDCAD_30M',
        'symbol_id': 30,  
        'symbol_precision': 5,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/NZDCAD_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_NZDCAD_QUICK.py',
        'buy_offset_percentage': 0.22,
        'sell_offset_percentage': 0.22,
        'stop_loss_percentage': 0.35,
        'take_profit_percentage': 0,
        'volume': 165000,  
    },
    {
        'label': 'HHLL_XAGUSD_240_MM_NET',
        'symbol_id': 42,  
        'symbol_precision': 2,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/XAGUSD_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_XAGUSD_240_MM.py',
        'buy_offset_percentage': 0.06,
        'sell_offset_percentage': 0.06,
        'stop_loss_percentage': 10,
        'take_profit_percentage': 0,
        'volume': 1700,  
    },
    {
        'label': 'HHLL_XAGUSD_240_MM_ORIGINAL',
        'symbol_id': 42,  
        'symbol_precision': 2,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/XAGUSD_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_XAGUSD_240_MM_ORIGINAL.py',
        'buy_offset_percentage': 0.06,
        'sell_offset_percentage': 0.06,
        'stop_loss_percentage': 10,
        'take_profit_percentage': 0,
        'volume': 1700,  
    },
    {
        'label': 'HHLL_XAGUSD_240_MM_HEDGE',
        'symbol_id': 42,  
        'symbol_precision': 2,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/XAGUSD_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_XAGUSD_240_MM_HEDGE.py',
        'buy_offset_percentage': 0.06,
        'sell_offset_percentage': 0.06,
        'stop_loss_percentage': 10,
        'take_profit_percentage': 0.05,
        'volume': 1700,  
    },
    {
        'label': 'HHLL_XAUCHF_MM_180_NET',
        'symbol_id': 10047,  
        'symbol_precision': 1,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/XAUCHF_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_XAUCHF_180_MM.py',
        'buy_offset_percentage': 0.04,
        'sell_offset_percentage': 0.04,
        'stop_loss_percentage': 1.5,
        'take_profit_percentage': 0,
        'volume': 40,  
    },
    {
        'label': 'HHLL_XAUCHF_MM_180_ORIGINAL',
        'symbol_id': 10047,  
        'symbol_precision': 1,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/XAUCHF_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_XAUCHF_MM_180_ORIGINAL.py',
        'buy_offset_percentage': 0.04,
        'sell_offset_percentage': 0.04,
        'stop_loss_percentage': 1.5,
        'take_profit_percentage': 0,
        'volume': 40,  
    },
    {
        'label': 'HHLL_XAUCHF_MM_180_HEDGE',
        'symbol_id': 10047,  
        'symbol_precision': 1,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/XAUCHF_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_XAUCHF_MM_180_HEDGE.py',
        'buy_offset_percentage': 0.04,
        'sell_offset_percentage': 0.04,
        'stop_loss_percentage': 1.5,
        'take_profit_percentage': 0,
        'volume': 40,  
    },
    {
        'label': 'HHLL_AEX_2H',
        'symbol_id': 10036,  
        'symbol_precision': 2,
        'depth_quotes_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/AEX_Quotes.py',
        'signal_file': 'C:/Users/Administrator/Desktop/Sonixen/Logs/HHLL_AEX_2H.py',
        'buy_offset_percentage': 0.05,
        'sell_offset_percentage': 0.05,
        'stop_loss_percentage': 0.685,
        'take_profit_percentage': 0,
        'volume': 103,  
    },
]
